{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "common.ingress.apiVer" . }}
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.ingress.labels" . | nindent 4 }}
  annotations:
    {{- include "common.ingress.annotations" . | nindent 4 }}
spec:
  {{- include "common.ingress.className" . | indent 2 }}
  {{- if .Values.ingress.certManagerIssuer }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.host | replace "." "-" | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "common.fullname" . }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "common.fullname" . }}
              servicePort: 80
              {{- end }}
{{- end }}
