# label setting
labels:
  default: true
  global: {}
  deploy: {}
  service: {}
  ingress: {}

# selector's label setting
selectorLabels:
  default: true
  custom: {}

annotations:
  global: {}
  deploy: {}
  service: {}
  ingress: {}

image:
  pullSecrets: ""
  repository: ""
  tag: "latest"
