emby:
  enabled: true

flaresolver:
  enabled: true

jackett:
  enabled: true

nzget:
  enabled: true

ombi:
  enabled: true

prowlarr:
  enabled: true

qbittorrent:
  enabled: true

radarr:
  enabled: true

sonarr:
  enabled: true

subfinder:
  enabled: true
