{{- if .Values.ingress.enabled -}}
{{- $fullName := include "frps.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- include "ingress.apiversion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "frps.labels" . | nindent 4 }}
  {{- if or .Values.ingress.autoHttpsIssuer .Values.ingress.annotations }}
  annotations:
  {{- if .Values.ingress.autoHttpsIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.autoHttpsIssuer | quote }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.autoHttpsIssuer }}
  tls:
    {{- if .Values.frps.httpEndpoint }}
    {{- include "frps.config.ingress.tls" . | indent 4 }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.frps.dashboard }}
    - host: {{ (include "frps.config.dashboard.host" .) | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "frps.fullname" . }}-http
              port:
                number: 8081
    {{- end }}
    {{- if .Values.frps.httpEndpoint }}
    {{- include "frps.config.ingress.hosts" . | indent 4 }}
    {{- end }}
{{- end }}
