apiVersion: v1
kind: Service
metadata:
  name: {{ include "frps.fullname" . }}-tcp-udp
  labels:
    {{- include "frps.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ include "frps.config.bind.tcp.ing" . }}
      targetPort: bind-tcp
      protocol: TCP
      name: bind-tcp
    {{- if .Values.frps.bind.udp }}
    - port: {{ include "frps.config.bind.udp.ing" . }}
      targetPort: bind-udp
      protocol: UDP
      name: bind-udp
    {{- end }}
    {{- if .Values.frps.ports }}
    {{- include "frps.config.svc.extPorts" . | indent 4 }}
    {{- end }}
  selector:
    {{- include "frps.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frps.fullname" . }}-http
  labels:
    {{- include "frps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.frps.dashboard.enabled }}
    - port: 8081
      targetPort: dashboard
      protocol: TCP
      name: frps-dashboard
    {{- end }}
    {{- if .Values.frps.httpEndpoint }}
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "frps.selectorLabels" . | nindent 4 }}
