{{- if .Values.enabled -}}
apiVersion: {{ include "common.deploy.apiVer" . }}
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.deploy.labels" . | nindent 4 }}
  {{- include "common.deploy.annotations" . | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.deploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.deploy.selectorLabels" . | nindent 8 }}
      {{- include "common.pod.annotations" . | indent 2 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flaresolverr.serviceAccountName" . }}
      containers:
      - image: {{ (include "common.image" .Values.image) | quote }}
        name: {{ .Chart.Name }}
        ports:
          - name: http
            containerPort: {{ .Values.containerPort | default 8191 }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort | default 8191 }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort | default 8191 }}
        env:
        - name: TEST_URL
          value: https://www.baidu.com
        - name: LOG_LEVEL
          value: info
        - name: PUID
          value: {{ .Values.UID | default 1000 }}
        - name: PGID
          value: {{ .Values.GID | default 1000 }}
        - name: TZ
          value: {{ .Values.TZ | default "Asia/Shanghai" }}
        {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}