{{- if and .Values.serviceAccount.create .Values.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flaresolverr.serviceAccountName" . }}
  labels:
    {{- include "common.serviceAccount.labels" . | nindent 4 }}
  {{- include "common.serviceAccount.annotations" . | indent 2 }}
{{- end }}
