apiVersion: {{ include "common.deploy.apiVer" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.deploy.labels" . | nindent 4 }}
  {{- include "common.deploy.annotations" . | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.deploy.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "common.fullname" . }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: bark-data
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- with .Values.persistence.selectorLabels }}
      selector:
        matchLabels:
{{ toYaml . | indent 10 }}
      {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.deploy.selectorLabels" . | nindent 8 }}
      {{- include "common.pod.annotations" . | indent 2 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "emby.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ (include "common.image" .Values.image) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 8096 }}
              protocol: TCP
          volumeMounts:
          - name: bark-data
            mountPath: /data
          livenessProbe:
            httpGet:
              path: /emby/system/info/public\?format\=json
              port: {{ .Values.containerPort | default 8096 }}
          readinessProbe:
            httpGet:
              path: /emby/system/info/public\?format\=json
              port: {{ .Values.containerPort | default 8096 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: bark-data
          emptyDir: {}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
