{{- if .Values.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullname" . }}-config-pvc
  labels:
    {{- include "common.serviceAccount.labels" . | nindent 4 }}
  {{- include "common.serviceAccount.annotations" . | indent 2 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}