apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.persistence.mediaPVCName }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
