apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullname" . }}-data-pvc
  labels:
    {{- include "common.serviceAccount.labels" . | nindent 4 }}
  {{- include "common.serviceAccount.annotations" . | indent 2 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}