{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bark.serviceAccountName" . }}
  labels:
    {{- include "common.serviceAccount.labels" . | nindent 4 }}
  {{- include "common.serviceAccount.annotations" . | indent 2 }}
{{- end }}
