{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # - port: 6881
    #   targetPort: bt-tcp
    #   protocol: TCP
    #   name: bt-tcp
    # - port: 6881
    #   targetPort: bt-udp
    #   protocol: UDP
    #   name: bt-udp
  selector:
    {{- include "common.deploy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-bt
  labels:
    {{- include "common.service.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.btPort | default 6881 }}
      targetPort: bt-tcp
      protocol: TCP
      name: bt-tcp
    - port: {{ .Values.btPort | default 6881 }}
      targetPort: bt-udp
      protocol: UDP
      name: bt-udp
  selector:
    {{- include "common.deploy.selectorLabels" . | nindent 4 }}
{{- end }}